# Generated by Django 4.0 on 2021-12-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConfig',
            new_name='profileConfig',
        ),
    ]
