# Generated by Django 4.0 on 2021-12-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_email'),
        ('dashboard', '0003_rename_userconfig_profileconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
