# Generated by Django 4.0 on 2021-12-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_blacklist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileconfig',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category'),
        ),
    ]
