# Generated by Django 4.0 on 2021-12-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_profileconfig_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileconfig',
            name='block',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
