# Generated by Django 4.0 on 2022-01-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_profileconfig_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileconfig',
            options={'ordering': ['cat_id']},
        ),
    ]
