# Generated by Django 4.0 on 2022-01-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_profileconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['freq']},
        ),
    ]
