# Generated by Django 4.0 on 2021-12-30 19:51

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
